// <auto-generated />
using System;
using Explorer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Explorer.Data.Migrations
{
    [DbContext(typeof(FootballDbContext))]
    [Migration("20241009133628_SeedDatabase")]
    partial class SeedDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.10");

            modelBuilder.Entity("Explorer.Domain.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Coaches");
                });

            modelBuilder.Entity("Explorer.Domain.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            TeamId = 1,
                            CreationDate = new DateTime(2024, 10, 9, 13, 36, 27, 770, DateTimeKind.Local).AddTicks(7688),
                            Name = "India"
                        },
                        new
                        {
                            TeamId = 2,
                            CreationDate = new DateTime(2024, 10, 9, 13, 36, 27, 770, DateTimeKind.Local).AddTicks(7719),
                            Name = "Bangladesh"
                        },
                        new
                        {
                            TeamId = 3,
                            CreationDate = new DateTime(2024, 10, 9, 13, 36, 27, 770, DateTimeKind.Local).AddTicks(7720),
                            Name = "Russia"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
